linux_install_paths:
  install: ~/.config/AIBS_MPE
  local_config: config
  local_log_config: logs
  python: /opt/mcpython3
services:
  log_server: 10.128.60.82:9000
  python_index: http://aibspi:3141/aibs/dev
  zookeeper: aibspi:2181
  issue_url: http://mpe-redirects/MPETracking
windows_install_paths:
  install: /ProgramData/AIBS_MPE
  local_config: config
  local_log_config: logs
  python: /mcpython3
apis:
  donor_info: http://lims2/donors/info/details.json?external_donor_name={}
  experiment_id: http://lims2/specimens/info/details.%s?experiment_id={}
  isi_experiment_prod: http://lims2/specimens/isi_experiment_details/{}.json
  isi_experiment_test: http://testlimswebc7:4800/specimens/isi_experiment_details/{}.json
  metadata: http://lims2/specimen_metadata.json?specimen_id={}
  projects_validation: http://lims2/projects.json?code={}
  save_visual_behavior_details: http://lims2/visual_behavior_details
  specimen_id: http://lims2/specimens/info/details.json?id={}
  specimen_name: http://lims2/specimens/info/details.json?specimen_name={}
  user_details: http://lims2/users.json?login={}
  visual_behavior_details: http://lims2/visual_behavior_details?donor_id={}
  well_name: http://lims2/specimens/info/details.json?carousel_well_name={}
configuration_file: //allen/aibs/mpe/configuration/lims_config.yml
default_paths:
  failed_trigger: //allen/programs/celltypes/production/incoming/mousecelltypes/failed_trigger
  file_ext: ecp,
  incoming: //allen/programs/braintv/production/incoming/neuralcoding
  lims_url: http://lims2
  root: //allen/programs/braintv/production
  trigger: //allen/programs/braintv/production/incoming/neuralcoding/trigger
neuropixel:
  file_ext: ecp
  notify:
  - davidre@alleninstitute.org
behavior_monitoring_string_exp: Check the pupil size? Screen brightness ok?
behavior_monitoring_string_hab: Check the pupil size? Screen brightness ok?
eye_dichroic_string: Eyetracking mirror in place, eye centered and face/body lighting
  appropriate?
MTrainData:
  Regimen: VisualBehaviorEPHYS_Task1G
  Regimen_Version: 0.1.1
  Stage_Keywords: []
  Experiment_Keywords:
  - EPHYS_1
  Experiment_Sessions:
    Day1:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/EPHYS_1_images_G_3uL_reward
    Day2:
      Keywords:
      - images_H
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/EPHYS_1_images_H_3uL_reward
  Habituation_Keywords:
  - HABITUATION_5, handoff_ready
  Habituation_Sessions:
    Habituation:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/HABITUATION_5_images_G_handoff_ready_3uL_reward
    1:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/HABITUATION_5_images_G_handoff_ready_5uL_reward
    2:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/HABITUATION_5_images_G_handoff_ready_5uL_reward
backup_location: allen\programs\mindscope\workgroups\np-exp
validation:
  environment: np_pipeline_validation
  params_directory: C:/users/svc_neuropix/Documents/GitHub/NP_pipeline_validation/rvalidation_params
  script: C:/users/svc_neuropix/Documents/GitHub/NP_pipeline_validation/run_validation_functions.py
pretest:
  mode: override_params
  path: C:/users/svc_neuropix/Documents/GitHub/NP_pipeline_validation/pretest_stim_params
expected_water_mass: 0.03
np_validation_python_path: C:/mcpython3/envs/np_pipeline_validation/python.exe
open-ephys:
  settings_dir: C:/Users/svc_neuropix/desktop/open-ephys-neuropix
new scale:
  log_path: C:/MPM_data/log.csv
max_experiment_duration_min: 180
active_probes:
- A
- B
- C
- D
- E
- F
components:
  # Cam3d:
  #   desc: Cam3d
  #   host: W10DTSM18278
  #   port: 11000
  #   version: 0.2.1
  Notes:
    desc: NotesApp
    host: W10DTSM18278
    port: 9999
    version: 0.1.0
  OpenEphys:  # old: should be unused once all old worflow code is updated
    desc: OpenEphys
    host: W10DT05501 
    version: 0.1.0
  Stim:  # old: should be unused once all old worflow code is updated
    desc: Stim # camstim 
    host: W10DTSM118294
    port: 5000
    version: 0.2.4
  Sync:  # old location: should be unused once all old worflow code is updated
    desc: Sync
    host: w10DTSM18306 
    port: 5000
    version: 1.3.1 # unused?
  MouseDirector:
    desc: MouseDirector
    host: w10DTSM18278 #orig # for btTest: try W10SV108131
    port: 9000 # for btTestL try 6000
    version: 0.8.0
    timeout: 1.0
  # Post Processing Validation Agent:
  #   desc: Post Processing Validation Agent
  #   host: localhost #W10SVAD0139 #localhost try W10DTSM18306
  #   port: 1234 #try 5000
  #   version: 0.1.0
  # Neuropixels Processing Agent W10DT05501:
  #   desc: Post Processing Validation Agent
  #   host:  localhost #W10SVAD0139 #localhost try W10DTSM18306
  #   port: 1234 #try 5000
  #   version: 0.1.0
  # Neuropixels Processing Assistant:
  #   desc: Post Processing Validation Agent
  #   host:  localhost #W10SVAD0139 #localhost try W10DTSM18306
  #   port: 1234 #try 5000
  #   version: 0.1.0
MVR:
  host: W10DTSM18278 # NP1
  port: 50000
hardware:
  newscale_controller_serial_numbers:
    A: 34027
    B: 31056
    C: 32141
    D: 32146
    E: 32139
    F: 32145
  face_camera_position:
    center_x_mm: -31.0
    center_y_mm: 124.7
    center_z_mm: 55.5
    rotation_x_deg: 3.6
    rotation_y_deg: -3.7
    rotation_z_deg: 0.0
  face_led_position:
    center_x_mm: -65.1
    center_y_mm: 115.8
    center_z_mm: 54.4
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  behavior_camera_position:
    center_x_mm: -214.9
    center_y_mm: -41.2
    center_z_mm: -20.8
    rotation_x_deg: 5.3
    rotation_y_deg: -10.9
    rotation_z_deg: 0.0
  behavior_led_position:
    center_x_mm: -229.7
    center_y_mm: 8.9
    center_z_mm: -10.3
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  eye_camera_position:
    center_x_mm: 102.8
    center_y_mm: 74.7
    center_z_mm: 31.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 2.8
  eye_led_position:
    center_x_mm: 246.0
    center_y_mm: 92.3
    center_z_mm: 52.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  led_position:
    center_x_mm: 246.0
    center_y_mm: 92.3
    center_z_mm: 52.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  screen_position:
    center_x_mm: 118.6
    center_y_mm: 86.2
    center_z_mm: 31.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
local_lims_head: \\W10DTSM18306\c$\ProgramData\AIBS_MPE\neuropixels_data
local_lims_location: ''
local_trigger_dir: \\W10DTSM18306\c$\ProgramData\AIBS_MPE\neuropixels\lims_trigger
mapped_lims_location: \\W10DTSM18306\c$\ProgramData\AIBS_MPE\neuropixels_data
openephys_drives:
  A: //W10DT05501/A
  B: //W10DT05501/A
  C: //W10DT05501/A
  D: //W10DT05501/B
  E: //W10DT05501/B
  F: //W10DT05501/B
possible_data_drives:
- A
- B
- L
probe_slots:
  A: 2
  B: 2
  C: 2
  D: 3
  E: 3
  F: 3
probe_type: PXI
slot_drives:
  2: A
  3: B
stim_file_dir: C:/ecephys_stimulus_scripts
stim_output_dir: C:/ProgramData/AIBS_MPE/camstim/output
sync_output_dir: C:/ProgramData/AIBS_MPE/sync/output
videomon_output_dir: C:/ProgramData/AIBS_MPE/MVR/data
final_depth_timer_s: 600
cameras:
- number: 1
  label: eye
  device_id: DEV_000F315BD375
- number: 2
  label: behavior
  device_id: DEV_000F315C1497
- number: 3
  label: face
  device_id: DEV_UNSPECIFIED
shared:
  water_calibration:
    NP-1-Stim:
      datetime: 2020-05-28 11:24:17
      intercept: 0.0166
      slope: 8.7254
    NP.1-Stim:
      datetime: 30/07/2020 10:06:57
      intercept: 0.0182
      slope: 8.4478
    W10DTSM118294:
      datetime: 30/07/2020 10:06:57
      intercept: 0.0182
      slope: 8.4478
