linux_install_paths:
  install: ~/.config/AIBS_MPE
  local_config: config
  local_log_config: logs
  python: /opt/mcpython3
services:
  log_server: 10.128.60.82:9000
  python_index: http://aibspi:3141/aibs/dev
  zookeeper: aibspi:2181
  issue_url: http://mpe-redirects/MPETracking
windows_install_paths:
  install: /ProgramData/AIBS_MPE
  local_config: config
  local_log_config: logs
  python: /mcpython3
apis:
  donor_info: http://lims2/donors/info/details.json?external_donor_name={}
  experiment_id: http://lims2/specimens/info/details.%s?experiment_id={}
  isi_experiment_prod: http://lims2/specimens/isi_experiment_details/{}.json
  isi_experiment_test: http://testlimswebc7:4800/specimens/isi_experiment_details/{}.json
  metadata: http://lims2/specimen_metadata.json?specimen_id={}
  projects_validation: http://lims2/projects.json?code={}
  save_visual_behavior_details: http://lims2/visual_behavior_details
  specimen_id: http://lims2/specimens/info/details.json?id={}
  specimen_name: http://lims2/specimens/info/details.json?specimen_name={}
  user_details: http://lims2/users.json?login={}
  visual_behavior_details: http://lims2/visual_behavior_details?donor_id={}
  well_name: http://lims2/specimens/info/details.json?carousel_well_name={}
configuration_file: //allen/aibs/mpe/configuration/lims_config.yml
default_paths:
  failed_trigger: //allen/programs/celltypes/production/incoming/mousecelltypes/failed_trigger
  file_ext: ecp,
  incoming: //allen/programs/braintv/production/incoming/neuralcoding
  lims_url: http://lims2
  root: //allen/programs/braintv/production
  trigger: //allen/programs/braintv/production/incoming/neuralcoding/trigger
neuropixel:
  file_ext: ecp
  notify:
  - davidre@alleninstitute.org
behavior_monitoring_string_exp: Check the pupil size? Screen brightness ok?
behavior_monitoring_string_hab: Check the pupil size? Screen brightness ok?
eye_dichroic_string: Eyetracking mirror in place, eye centered and face/body lighting
  appropriate?
MTrainData:
  Regimen: VisualBehaviorEPHYS_Task1G
  Regimen_Version: 0.1.1
  Stage_Keywords: []
  Experiment_Keywords:
  - EPHYS_1
  Experiment_Sessions:
    Day1:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/EPHYS_1_images_G_3uL_reward
    Day2:
      Keywords:
      - images_H
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/EPHYS_1_images_H_3uL_reward
  Habituation_Keywords:
  - HABITUATION_5, handoff_ready
  Habituation_Sessions:
    Habituation:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/HABITUATION_5_images_G_handoff_ready_3uL_reward
    1:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/HABITUATION_5_images_G_handoff_ready_5uL_reward
    2:
      Keywords:
      - images_G
      - 3uL_reward
      Full_String: VisualBehaviorEPHYS_Task1G_v0.1.1/HABITUATION_5_images_G_handoff_ready_5uL_reward
backup_location: allen\programs\mindscope\workgroups\np-exp
validation:
  environment: np_pipeline_validation
  params_directory: C:/users/svc_neuropix/Documents/GitHub/NP_pipeline_validation/rvalidation_params
  script: C:/users/svc_neuropix/Documents/GitHub/NP_pipeline_validation/run_validation_functions.py
pretest:
  mode: override_params
  path: C:/users/svc_neuropix/Documents/GitHub/NP_pipeline_validation/pretest_stim_params
serialized_states_folder: C:/ProgramData/AIBS_MPE/wfltk/resume
expected_water_mass: 0.03
np_validation_python_path: C:/mcpython3/envs/np_pipeline_validation/python.exe
open-ephys:
  settings_dir: C:/Users/svc_neuropix/desktop/open-ephys-neuropix
new scale:
  log_path: C:/MPM_data/log.csv
max_experiment_duration_min: 180
scripts_path: //allen/aibs/mpe/Software/np_passive_scripts
active_probes:
- A
- B
- C
- D
- E
- F
components:
  Cam3d:
    desc: Cam3d
    host: w10dtsm112722
    port: 11000
    version: 0.1.3.post0+g9879442.b87201
  Notes:
    desc: NotesApp
    host: w10dtsm112722
    port: 9999
    version: 0.1.0
  OpenEphys:
    desc: OpenEphys
    host: w10dt05515
    version: 0.1.0
  Stim:
    desc: Stim
    host: w10dtsm112721
    port: 5000
    version: 0.2.4
  Sync:
    desc: Sync
    host: w10dtsm112719
    port: 5000
    version: 1.3.1
  MouseDirector:
    desc: MouseDirector
    host: w10dtsm112722
    port: 9000
    version: 0.8.0
MVR:
  host: w10dtsm112722
  port: 50000
hardware:
  newscale_controller_serial_numbers:
    A: 32148
    B: 32142
    C: 32144
    D: 32149
    E: 32135
    F: 24273
  face_camera_position:
    center_x_mm: -31.0
    center_y_mm: 124.7
    center_z_mm: 55.5
    rotation_x_deg: 3.6
    rotation_y_deg: -3.7
    rotation_z_deg: 0.0
  face_led_position:
    center_x_mm: -65.1
    center_y_mm: 115.8
    center_z_mm: 54.4
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  behavior_camera_position:
    center_x_mm: -214.9
    center_y_mm: -41.2
    center_z_mm: -20.8
    rotation_x_deg: 5.3
    rotation_y_deg: -10.9
    rotation_z_deg: 0.0
  behavior_led_position:
    center_x_mm: -229.7
    center_y_mm: 8.9
    center_z_mm: -10.3
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  eye_camera_position:
    center_x_mm: 102.8
    center_y_mm: 74.7
    center_z_mm: 31.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 2.8
  eye_led_position:
    center_x_mm: 246.0
    center_y_mm: 92.3
    center_z_mm: 52.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  led_position:
    center_x_mm: 246.0
    center_y_mm: 92.3
    center_z_mm: 52.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
  screen_position:
    center_x_mm: 118.6
    center_y_mm: 86.2
    center_z_mm: 31.6
    rotation_x_deg: 0.0
    rotation_y_deg: 0.0
    rotation_z_deg: 0.0
local_lims_head: \\w10dtsm112719\c$\ProgramData\AIBS_MPE\neuropixels_data
local_lims_location: ''
local_trigger_dir: \\w10dtsm112719\c$\ProgramData\AIBS_MPE\neuropixels\lims_trigger
mapped_lims_location: \\w10dtsm112719\c$\ProgramData\AIBS_MPE\neuropixels_data
openephys_drives:
  A: //W10DT05515/A
  B: //W10DT05515/A
  C: //W10DT05515/A
  D: //W10DT05515/B
  E: //W10DT05515/B
  F: //W10DT05515/B
possible_data_drives:
- A
- B
- L
probe_slots:
  A: 2
  B: 2
  C: 2
  D: 3
  E: 3
  F: 3
probe_type: PXI
slot_drives:
  2: A
  3: B
stim_file_dir: C:/ecephys_stimulus_scripts
stim_output_dir: C:/ProgramData/AIBS_MPE/camstim/output
sync_output_dir: C:/ProgramData/AIBS_MPE/sync/output
videomon_output_dir: C:/ProgramData/AIBS_MPE/MVR/data
final_depth_timer_s: 600
cameras:
- number: 1
  label: behavior
  device_id: DEV_000F315BC5DA
- number: 2
  label: eye
  device_id: DEV_000F315CEBC4
- number: 3
  label: face
  device_id: DEV_000F315CBCFD
shared:
  water_calibration:
    NP.0-Stim:
      datetime: 31/07/2020 14:28:53
      intercept: 0.0167
      slope: 9.0659
    W10DTSM112721:
      datetime: 31/07/2020 14:28:53
      intercept: 0.0167
      slope: 9.0659
    datetime: 12/07/2020 15:40:03
    intercept: 0.0157
    slope: 10.0103
