# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ephys_edi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mpetk.aibsmw import aibsmw_messages_pb2 as aibsmw__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ephys_edi.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x65phys_edi.proto\x1a\x15\x61ibsmw_messages.proto\"6\n\x13request_system_info\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\"d\n\x0bsystem_info\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\x12\x19\n\x11software_revision\x18\x02 \x02(\t\x12\x19\n\x11hardware_revision\x18\x03 \x02(\t\"8\n\x15request_system_status\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\"\xbe\x01\n\rsystem_status\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\x12\x31\n\x06status\x18\x02 \x02(\x0e\x32\x1a.system_status.status_type:\x05READY\x12\x0f\n\x07message\x18\x03 \x02(\t\x12\x19\n\x11source_message_id\x18\x04 \x02(\t\"-\n\x0bstatus_type\x12\t\n\x05READY\x10\x00\x12\x08\n\x04\x42USY\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"C\n\x12set_data_file_path\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\x12\x0c\n\x04path\x18\x02 \x02(\t\"H\n\x17open_configuration_file\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\x12\x0c\n\x04path\x18\x02 \x02(\t\"\x7f\n\x0b\x61\x63quisition\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\x12*\n\x07\x63ommand\x18\x02 \x02(\x0e\x32\x19.acquisition.command_type\"#\n\x0c\x63ommand_type\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\"{\n\trecording\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.message_header\x12(\n\x07\x63ommand\x18\x02 \x02(\x0e\x32\x17.recording.command_type\"#\n\x0c\x63ommand_type\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01')
  ,
  dependencies=[aibsmw__messages__pb2.DESCRIPTOR,])



_SYSTEM_STATUS_STATUS_TYPE = _descriptor.EnumDescriptor(
  name='status_type',
  full_name='system_status.status_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=404,
  serialized_end=449,
)
_sym_db.RegisterEnumDescriptor(_SYSTEM_STATUS_STATUS_TYPE)

_ACQUISITION_COMMAND_TYPE = _descriptor.EnumDescriptor(
  name='command_type',
  full_name='acquisition.command_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=686,
  serialized_end=721,
)
_sym_db.RegisterEnumDescriptor(_ACQUISITION_COMMAND_TYPE)

_RECORDING_COMMAND_TYPE = _descriptor.EnumDescriptor(
  name='command_type',
  full_name='recording.command_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=686,
  serialized_end=721,
)
_sym_db.RegisterEnumDescriptor(_RECORDING_COMMAND_TYPE)


_REQUEST_SYSTEM_INFO = _descriptor.Descriptor(
  name='request_system_info',
  full_name='request_system_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='request_system_info.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=96,
)


_SYSTEM_INFO = _descriptor.Descriptor(
  name='system_info',
  full_name='system_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='system_info.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='software_revision', full_name='system_info.software_revision', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardware_revision', full_name='system_info.hardware_revision', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=198,
)


_REQUEST_SYSTEM_STATUS = _descriptor.Descriptor(
  name='request_system_status',
  full_name='request_system_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='request_system_status.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=256,
)


_SYSTEM_STATUS = _descriptor.Descriptor(
  name='system_status',
  full_name='system_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='system_status.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='system_status.status', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='system_status.message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_message_id', full_name='system_status.source_message_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYSTEM_STATUS_STATUS_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=449,
)


_SET_DATA_FILE_PATH = _descriptor.Descriptor(
  name='set_data_file_path',
  full_name='set_data_file_path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='set_data_file_path.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='set_data_file_path.path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=518,
)


_OPEN_CONFIGURATION_FILE = _descriptor.Descriptor(
  name='open_configuration_file',
  full_name='open_configuration_file',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='open_configuration_file.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='open_configuration_file.path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=592,
)


_ACQUISITION = _descriptor.Descriptor(
  name='acquisition',
  full_name='acquisition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='acquisition.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='acquisition.command', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACQUISITION_COMMAND_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=594,
  serialized_end=721,
)


_RECORDING = _descriptor.Descriptor(
  name='recording',
  full_name='recording',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='recording.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='recording.command', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RECORDING_COMMAND_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=723,
  serialized_end=846,
)

_REQUEST_SYSTEM_INFO.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_SYSTEM_INFO.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_REQUEST_SYSTEM_STATUS.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_SYSTEM_STATUS.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_SYSTEM_STATUS.fields_by_name['status'].enum_type = _SYSTEM_STATUS_STATUS_TYPE
_SYSTEM_STATUS_STATUS_TYPE.containing_type = _SYSTEM_STATUS
_SET_DATA_FILE_PATH.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_OPEN_CONFIGURATION_FILE.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_ACQUISITION.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_ACQUISITION.fields_by_name['command'].enum_type = _ACQUISITION_COMMAND_TYPE
_ACQUISITION_COMMAND_TYPE.containing_type = _ACQUISITION
_RECORDING.fields_by_name['header'].message_type = aibsmw__messages__pb2._MESSAGE_HEADER
_RECORDING.fields_by_name['command'].enum_type = _RECORDING_COMMAND_TYPE
_RECORDING_COMMAND_TYPE.containing_type = _RECORDING
DESCRIPTOR.message_types_by_name['request_system_info'] = _REQUEST_SYSTEM_INFO
DESCRIPTOR.message_types_by_name['system_info'] = _SYSTEM_INFO
DESCRIPTOR.message_types_by_name['request_system_status'] = _REQUEST_SYSTEM_STATUS
DESCRIPTOR.message_types_by_name['system_status'] = _SYSTEM_STATUS
DESCRIPTOR.message_types_by_name['set_data_file_path'] = _SET_DATA_FILE_PATH
DESCRIPTOR.message_types_by_name['open_configuration_file'] = _OPEN_CONFIGURATION_FILE
DESCRIPTOR.message_types_by_name['acquisition'] = _ACQUISITION
DESCRIPTOR.message_types_by_name['recording'] = _RECORDING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request_system_info = _reflection.GeneratedProtocolMessageType('request_system_info', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_SYSTEM_INFO,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:request_system_info)
  ))
_sym_db.RegisterMessage(request_system_info)

system_info = _reflection.GeneratedProtocolMessageType('system_info', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEM_INFO,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:system_info)
  ))
_sym_db.RegisterMessage(system_info)

request_system_status = _reflection.GeneratedProtocolMessageType('request_system_status', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_SYSTEM_STATUS,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:request_system_status)
  ))
_sym_db.RegisterMessage(request_system_status)

system_status = _reflection.GeneratedProtocolMessageType('system_status', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEM_STATUS,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:system_status)
  ))
_sym_db.RegisterMessage(system_status)

set_data_file_path = _reflection.GeneratedProtocolMessageType('set_data_file_path', (_message.Message,), dict(
  DESCRIPTOR = _SET_DATA_FILE_PATH,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:set_data_file_path)
  ))
_sym_db.RegisterMessage(set_data_file_path)

open_configuration_file = _reflection.GeneratedProtocolMessageType('open_configuration_file', (_message.Message,), dict(
  DESCRIPTOR = _OPEN_CONFIGURATION_FILE,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:open_configuration_file)
  ))
_sym_db.RegisterMessage(open_configuration_file)

acquisition = _reflection.GeneratedProtocolMessageType('acquisition', (_message.Message,), dict(
  DESCRIPTOR = _ACQUISITION,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:acquisition)
  ))
_sym_db.RegisterMessage(acquisition)

recording = _reflection.GeneratedProtocolMessageType('recording', (_message.Message,), dict(
  DESCRIPTOR = _RECORDING,
  __module__ = 'ephys_edi_pb2'
  # @@protoc_insertion_point(class_scope:recording)
  ))
_sym_db.RegisterMessage(recording)


# @@protoc_insertion_point(module_scope)
